---
# Install necessary packages

- name: Enable apt repositories
  apt_repository:
    repo={{ item }}
    state=present
  with_items:
    - ppa:fcwu-tw/ppa
    - ppa:git-core/ppa
    - ppa:nginx/stable
    - ppa:ondrej/php

- name: Install standard packages
  apt:
    name={{ item }}
    state=present
  with_items: "{{ packages_standard }}"

- name: Install php packages
  apt:
    name={{ item }}
    state=present
  with_items: "{{ packages_php }}"

- name: Upgrade all packages
  apt:
    upgrade=dist

- name: Upgrade /usr/bin/pip
  shell: /usr/bin/pip install --upgrade pip
  ignore_errors: yes

- name: Clean packages
  shell: apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
