---
# Set up supervisord

- name: Pip | Install supervisord
  shell: /usr/local/bin/pip install --upgrade supervisor

- name: Pip | Install requests[security]
  shell: /usr/local/bin/pip install 'requests[security]'

- name: Supervisord | Copy configs
  template:
    src="etc/supervisord.conf"
    dest=/etc/supervisord.conf
    owner=root
    group=root
    mode=0744

- file:
    path=/var/log/supervisord
    state=directory
    owner=root
    group=root

- file:
    path=/var/run/php
    state=directory
    owner=root
    group=root
