---
# Set up vim

- name: create .vim/bundle directory
  file:
    path=/root/.vim/bundle
    owner=root
    group=root
    state=directory

- name: install vundle
  git:
    repo=git://github.com/gmarik/Vundle.vim
    dest=/root/.vim/bundle/vundle
    accept_hostkey=yes

- name: copy over vim installation file
  copy:
    src=root/bundle-install.vimrc
    dest=/root/bundle-install.vimrc
    owner=root
    group=root

- name: install vim bundles
  command: vim -u /root/bundle-install.vimrc +BundleInstall! +qall

- name: remove vim installation file
  file:
    path="/root/bundle-install.vimrc"
    state=absent
