app:
  build: .
  ports:
    - "80"
  expose:
    - "80"
  volumes:
    - .:/site
    - ./docker:/docker
    - ./.zsh_history:/root/.zsh_history
    - ./docker/nginx/conf.d/example.conf:/etc/nginx/conf.d/example.conf
  environment:
    - VIRTUAL_HOST=example.docker
